### ISSUE TITLE
official twitter typeahead javascript API is not available in this package

### ISSUE THREAD

**Issue by Alino** [sergeyt/meteor-typeahead#106]
this [official twitter typeahead javascript api](https://github.com/twitter/typeahead.js/blob/master/doc/jquery_typeahead.md#api) is undefined within this package, currently I would really need to use some of those api calls. Are there any plans to implement this, or does anyone has a workaround? Or any hint on how to make it possible so maybe I could try to do it and commit?

**Comment by sergeyt** [comment]
@Alino please see the working example with usage of typeahead API in demo app. Note to open the dropdown menu you should set the value first or try to specify `data-min-length=0` if you want to open the menu without input query.

**Comment by Alino** [comment]
Thank you. So my problem is that typeahead is undefined when I try ```$('.typeahead').typeahead```
https://forums.meteor.com/t/jquery-plugins-are-undefined-in-global-client-scope-when-they-are-loaded-from-packages/9652
