### ISSUE TITLE
Helpers for select/autocomplete don't fire in 0.11.1_4 but 0.11.1_3 works fine.

### ISSUE THREAD

**Issue by ciwolsey** [sergeyt/meteor-typeahead#108]
After upgrading to 0.11.1_4 from 0.11.1_3 the helpers are not firing on select/autocomplete. Downgrading to 0.11.1_3 solves the problem.

**Comment by oliroy** [comment]
+1 same issue

**Comment by sergeyt** [comment]
Name of `data-` attributes is changed. Please see [docs](https://github.com/sergeyt/meteor-typeahead/blob/master/docs.md). Demo app has working example. Old names could be easy to add. Please PR to fix this API breaking change.

**Comment by ciwolsey** [comment]
Great. Thanks
