### ISSUE TITLE
No results returned when data-limit is specified

### ISSUE THREAD

**Issue by jasonnathan** [sergeyt/meteor-typeahead#109]
Hi there, this package works fine when I define the element's attributes like this

    <input autofill="off" autocomplete="off" type="search" class="typeahead"
        data-hightlight="true" 
        data-source="getItems" 
        data-selected="addItems" 
        data-value-key="item_name"
        data-template="itemSuggestion"                           
        value="{{escapedName}}">

Works perfectly. But as soon as I add `data-limit="20"` attribute, the dropdown never shows. 
Server returns 20 results either way, so no issues there. 

Would really appreciate any pointers debugging.

**Comment by oliroy** [comment]
Check out https://github.com/twitter/typeahead.js/issues/1232.  It is a bug in the current version of twitter typeahead.js .  Basically you need to set the data-limit to 40 or higher to make sure your results always show if your server returns up to 20 results.

**Comment by jasonnathan** [comment]
Thanks, it works with 40 :)
