### ISSUE TITLE
Typeahead initialized but no results are returned

### ISSUE THREAD

**Issue by jasenkoh** [sergeyt/meteor-typeahead#111]
Hi,

I am able to initialize typeahead and I am able to read input value in helper but tt-dataset is constantly empty.

Am I missing anything?

```html
<template name="navSearch">
  <div class="row">
    <div class="col-xs-12">
      <div class="input-group input-group-lg inner-addon" style="width:100%">
        <input class="form-control typeahead" name="repo" type="text"
               placeholder="open source projects by Twitter"
               autocomplete="off" spellcheck="off"
               data-source="repos" data-template="repo"/>
      </div>
      <!-- /input-group -->
    </div>
    <!-- /.col-xs-12 -->
  </div>
  <!-- /.row -->
</template>
<template name="repo">
       <p class="repo-name">{{name}}</p>
</template>
```

```coffescript
Template.navSearch.onRendered ->
  Meteor.typeahead.inject()
Template.navSearch.helpers
  repos: (q) ->
    console.log q
    return [
      {name: 'foo'}
      {name: 'bar'}
    ]

```

**Comment by sergeyt** [comment]
@jasenkoh try to use `data-value-key="name"` or return objects with `value` property which is used by default

**Comment by jasenkoh** [comment]
@sergeyt you were right, I was missing `value` property, but also I had to remove `q` property from repos helper. Although I've tried with array of values (standard example) and it didn't work, again while  `q` was present, once I removed  `q` I was able to see results. Not sure if da

```javascript
repos: (query, sync, callback) ->
    callback Repos.search(query).fetch().map (v) ->  { value: v.title }
```

**Comment by sergeyt** [comment]
@jasenkoh helper function could be of two forms:

1. without arguments expecting array of suggestions
2. with 3 arguments `(query, sync, async)` for custom/async search of suggestions

Also please see [the docs](https://github.com/sergeyt/meteor-typeahead/blob/master/docs.md) for more information.
