### ISSUE TITLE
Server side search does not work

### ISSUE THREAD

**Issue by janvydra** [sergeyt/meteor-typeahead#115]
Hello,

I have been trying hard to use server side search in a small project that I am doing, but it does not work. The search helper function gets called twice after injection and never after that. I thought I did something wrong in my code, but I found out even the <b>demo</b> of server search does not work - please see last input on the demo page. Problem with changed API?

It seems that in the helper definition:

Template.foo.helpers({
       search: function(query, sync, callback){
....
all of query, sync or callback are undefined when this gets called, and it gets called only once after rendering...

Best regards
Jan

**Comment by sergeyt** [comment]
@janvydra please try again, it seems meteor now requires that Meteor.methods should be declared in server and client. On client it is used to generate stubs.

**Comment by shapiromatron** [comment]
@janvydra I just ran the demo app and it took around 10 minutes for the server to populate the collection.  After it was populated the server-side search worked fine. The code was just updated this morning to work with version 1.2.0.2; if you were trying to run the demos using that version then all would have been broken.

**Comment by janvydra** [comment]
Thank you, it started to work now.
Jan
