### ISSUE TITLE
Meteor - sergeyt:typeahead - Not injecting when inside an {{#each}}

### ISSUE THREAD

**Issue by atheriault** [sergeyt/meteor-typeahead#126]
I have several instances of sergeyt:typeahead working in my webapp. However today I am building a table out of data from query. One of the columns needs to allow for possibly selecting from a collection or if the user wants to enter their own value. 

This has worked for me in other parts. Now it appears that when using an {{#each}} statement in the html and when the typeahead is inside the {{#each}} that it does not receive the injecting.

I believe this may be due to the fact that inject is typically done on the rendered which is run before the {{#each}} has run and created the dom elements. And if that is the case how would I go about then placing the inject on these newly generated elements?

**Comment by sergeyt** [comment]
@atheriault try to place typeahead input into separate template and init it with Meteor.typeahead in `rendered` event handler in this template.

**Comment by sergeyt** [comment]
AFAIR this is fixed now
