### ISSUE TITLE
Typeahead not activated?

### ISSUE THREAD

**Issue by isocra** [sergeyt/meteor-typeahead#13]
This might be the same as issue #8.

I've installed typeahead using `mrt add typeahead` and then attaching the typeahead class to one of my input fields:

```
<input type="text" class="form-control typeahead" name="clubName" autocomplete="off" spellcheck="off" data-source="clubs"/>
```

Unfortunately nothing happens when I type in.

If I cd into packages/typeahead/demo and run your demo it works fine. I can put a breakpoint on line 40 of index.js and the breakpoint is reached when I refresh the page.

However, if I run my own app and put a breakpoint in the same place, it's never called.

Any idea why it's not working? What else do I need to do?

Thanks

**Comment by nickeleres** [comment]
I got it to work by creating a publication for the data the template helper returns to the client.  You have to subscribe to the datasource if you remove autopublish package (which you should).

**Comment by Jayuda** [comment]
Hello @titocosta and @isocra : I have add Meteor.typeahead.inject() on Template.myTemplate.rendered but sometimes work and others times not working.
Any sugestions ?
