### ISSUE TITLE
notFound Template

### ISSUE THREAD

**Issue by romant** [sergeyt/meteor-typeahead#136]
Does anyone have an example of an implementation ? 

Don't see if it's part of the `data-` element; or even supported with this wrapper.

Thank you

**Comment by sergeyt** [comment]
@romant see [demo app](https://github.com/sergeyt/meteor-typeahead/blob/master/demo/demo.html#L142), it has sample using `empty` template.

**Comment by romant** [comment]
Thank you @sergeyt.
