### ISSUE TITLE
Typeahead with FlowRouter

### ISSUE THREAD

**Issue by DevanB** [sergeyt/meteor-typeahead#137]
I moved our app (which uses meteor-typeahead) to FlowRouter this weekend. No issues were happening prior to the move, but after the move I've started seeing check/Match errors.

I may be wrong, but it seems when the app is loaded up (on the templates that are loaded) the helper is being called which invokes the Meteor method even before the user actually types anything into the box. Therefore my matches are expecting a string, but are receiving an object which is undefined.

Any ideas on how to fix this?

**Comment by DevanB** [comment]
This issue is actually happening in Iron Router also. Unless it coincides with the actual package update that happened recently, I believe it may be my mistake. Therefore, I'm closing the issue for now. Thanks

**Comment by DevanB** [comment]
So I actually figured out that the `kadira:debug` package is the root of the problems. When I add `kadira:debug`, I start seeing the Match/check errors when the app reloads. After I remove `kadira:debug` the Match/check errors stop after the app reloads.

@arunoda @kadirahq

**Comment by arunoda** [comment]
@DevanB could you send me the stack trace you got? I'm happy to investigate a bit.

**Comment by DevanB** [comment]
Sure! I'll gather that and I have a screenshot of Kadira Debug telling some information too. Thanks Arunoda!

**Comment by arunoda** [comment]
Great.

**Comment by DevanB** [comment]
@arunoda

Here is a gist of the only stack trace I have (match errors), some bits of code that were being invoked and an image of the Kadira Debug report for what was actually being passed in on application restart after adding `kadira:debug`. If you have any other questions, feel free to ask.

https://gist.github.com/DevanB/b79d2f6f6c3bdcf268f6

**Comment by arunoda** [comment]
Thanks. Let me check on this.
