### ISSUE TITLE
Could I use with "AutoForm"?

### ISSUE THREAD

**Issue by thearabbit** [sergeyt/meteor-typeahead#139]
I would like to create addon for `autoform` like `select2, datepicker...`, but I don't understand.
Have any?
Please help me.

**Comment by sergeyt** [comment]
This package is wrapper around this twitter [typeahead.js](https://github.com/twitter/typeahead.js) jquery plugin. It works only for text `<input/>` element defined inside any Blaze template. See [the docs](https://github.com/sergeyt/meteor-typeahead/blob/master/docs.md) how configure your input and initialize the plugin. Also see the [demo app](https://github.com/sergeyt/meteor-typeahead/blob/master/demo/demo.html) to generate more ideas how it works.

**Comment by thearabbit** [comment]
thanks for your reply.
I will try to create `autoFrom addon` from this.
