### ISSUE TITLE
Typeahead always shows only 5 suggestions maximum

### ISSUE THREAD

**Issue by sainipradeep** [sergeyt/meteor-typeahead#156]
Hello, 
Typeahead always shows only 5 suggestions maximum. How to change sufficient count.

**Comment by tdotholla** [comment]
check this page on the typeahead docs: 
[Datasets](https://github.com/twitter/typeahead.js/blob/master/doc/jquery_typeahead.md#datasets)

> `limit` – The max number of suggestions to be displayed. Defaults to `5`.

**Comment by alexvnz** [comment]
Just adding data-limit="10" to input properties works for me
