### ISSUE TITLE
typeahead-wait-ms not supported?

### ISSUE THREAD

**Issue by jwjordan** [sergeyt/meteor-typeahead#46]
Wondering if the option for typeahead-wait-ms is supported in the latest version?  I have everything working as expected so far, but I am trying to delay my API requests so that when I type a search term, I'm not firing an API call for every single letter that is typed.  I think that defining typeahead-wait-ms is the correct solution, but it doesn't appear that it has any effect when defined in the input like this:

<input class="form-control typeahead" id="search" name="search" type="text"
                    placeholder="Type to query"
                    autocomplete="off" spellcheck="off"
                    data-source="search" data-selected="selected" data-template="searchResults"
                    typeahead-wait-ms="1000"/>

**Comment by s7dhansh** [comment]
any change in this status? or do we still have to roll out our own implementation

**Comment by leizard** [comment]
Hi @sergeyt. I implement `data-source` with `underscore throttle` like this:

```
    searchCustomerName: _.throttle(function(query, sync, callback) {
        Meteor.call('customers.search', 'name', query, {limit: 10}, function(err, res) {
            if (err) {
                console.log(err);
                return Namsoft.show.error(err.message);
            }
            callback(Customers.getSuggestionList('name', res));
        });
    }, 500)
```

But I have error: ` callback is not a function`
Do you have any idea ?

**Comment by s7dhansh** [comment]
Somehow, the function returned by _.bedbounce or throttle do not work. I did not have the time to go into deep, so rolled out my own implementation
```
var searchFunc = function() {
        let methodFunc; // define your actual meteor call or actual search method here
	let handle, wait = 200; // change this waitTime to suit your need
	return function(query, sync, callback) {
		if ((query || "").length < 3) return;
		var later = function() {
			handle = null;
			methodFunc(query, callback);
		};
		if (handle) clearTimeout(handle);
		handle = setTimeout(later, wait);
	};
};

searchCustomerName: searchFunc();
```
