### ISSUE TITLE
How should I clear an open list of suggestions?

### ISSUE THREAD

**Issue by flippyhead** [sergeyt/meteor-typeahead#48]
I've got a search input. Once you start typing and suggestions appear, if you continue typing out a matching suggestion (without actually selecting it) the suggestion list / drop-down doesn't go away. I'd like to be able to manually clear it in this case but I'm not seeing how. Thanks!

**Comment by sergeyt** [comment]
@flippyhead according to [typeahead.js](https://github.com/twitter/typeahead.js/blob/master/doc/jquery_typeahead.md#specification) docs if there is no suggestions the typeahead should:

```
close dropdown menu
clear suggestions from dropdown menu
remove hint
```

Maybe in your case suggestion function behaves incorrectly.
