### ISSUE TITLE
minLength 0

### ISSUE THREAD

**Issue by vladblindu** [sergeyt/meteor-typeahead#49]
Hello,
Is there a way to have the drop down open on focus?
The way select2 works.

Thanks

**Comment by sergeyt** [comment]
hi @vladblindu , here are related links and issues:
* http://stackoverflow.com/questions/19797370/twitter-typeahead-js-show-all-options-when-click-focus
* http://jsfiddle.net/5xxYq/ as possible solution
* [PR #390](https://github.com/twitter/typeahead.js/pull/390), [PR #719](https://github.com/twitter/typeahead.js/pull/719)

Fix for minLength=0 could be included in typeahead.js v0.11. Now I am trying to find and commit a hackish solution.

**Comment by sergeyt** [comment]
@vladblindu please try to use v0.10.5_8 which includes the fix for this issue.
