### ISSUE TITLE
Return typeahead instance when calling Meteor.typeahead(<element>)

### ISSUE THREAD

**Issue by schickm** [sergeyt/meteor-typeahead#52]
Currently the Meteor.typeahead function returns nothing.  Was that intentional? I'd be nice it if returned the typeahead instance so that someone can access the internal functions of the instance when needed.

Would you accept a PR for that?

**Comment by schickm** [comment]
Never mind, solved my own probably by reading the docs for typeahead.  You can just call .typeahead on a jQuery selector:
```
$('[name=task]').typeahead('val', '');
```

I was trying to figure out how to blank out the input after selection. Just setting the value of the input worked until the input lost focus, then typeahead would stuff the last selected value back in the input.

**Comment by sergeyt** [comment]
@schickm I think it is good idea and PR will be accepted. I could do that myself shortly.
