### ISSUE TITLE
data-hint – If false, the typeahead will not show a hint. Defaults to true.

### ISSUE THREAD

**Issue by winstoncse** [sergeyt/meteor-typeahead#53]
Thanks for your great meteor typeahead package : ]

I was trying to config the typeahead to show the autocomplete hint, so it will autocomplete the query if a user press tab, but it was not shown in the demo (http://typeahead.meteor.com/) as well. 

After looking deeper, seems like it works if I specify data attr  'data-hint' to be 'true'.

According to your documentation(https://github.com/sergeyt/meteor-typeahead/blob/master/docs.md) for typeahead options data-hint – If false, the typeahead will not show a hint. Defaults to true.

Seems like the defaults is false for some reason 
   index.js (https://github.com/sergeyt/meteor-typeahead/blob/master/index.js)
	var hint = Boolean($e.data('hint')) || false;

Cheers!
Winston

**Comment by sergeyt** [comment]
@winstoncse thanks for bug report, fixed in v0.10.5_12
