### ISSUE TITLE
data-source function never calls.  it never activates for me.

### ISSUE THREAD

**Issue by boris-petrov1214** [sergeyt/meteor-typeahead#55]
the package never works for me.
I am not using bootstrap. i am using materialize. is it the problem?

**Comment by boris-petrov1214** [comment]
do i have to use Meteor.typeahead.inject(); ?
 `<input class="form-control typeahead" name="search" type="text" placeholder="Type to query"`
                           autocomplete="off" spellcheck="off"
                          ` data-source="nba"/>`

Meteor.myProperTemplate.nba = function() {
//it never calls here.
}

**Comment by sergeyt** [comment]
@boris-petrov1214 this package does not include any CSS styles so it should work with meterialize also, but you need to define styles for typeahead inputs like in demo app. To activate typeahead behavior to your input you could either use Meteor.typeahead or Meteor.typeahead.inject in your template `rendered` event handler.

**Comment by boris-petrov1214** [comment]
@sergeyt 

Thanks it works.

**Comment by boris-petrov1214** [comment]
I have one question.

**Comment by hamoid** [comment]
It would be very helpful to mention how to enable it in the readme. Otherwise it looks like installing the addon and including the css should be enough. I've been half hour trying to figure out why it doesn't work.
