### ISSUE TITLE
Support global template helpers for data-sources attribute

### ISSUE THREAD

**Issue by woniesong92** [sergeyt/meteor-typeahead#67]
Right now, we only search for the helper functions inside the current template.
We should also search in `UI._globalHelpers` to see if the function specified in `data-sources` is available.

**Comment by sergeyt** [comment]
@woniesong92 I think searching only in current template is enough for most use cases, also it makes template to be self-sufficient without dependency on any global stuff. However we could discuss to support explicit `global:` prefix in `data-source` attribute to specify use of function from `UI._globalHelpers`.
