### ISSUE TITLE
Autocomplete template doesn't look right

### ISSUE THREAD

**Issue by tlau** [sergeyt/meteor-typeahead#69]
![image](https://cloud.githubusercontent.com/assets/442971/7150393/50dd4274-e2cf-11e4-950b-7a72d783181d.png)

I'm trying to use the typeahead widget to make a column in a database table editable using autocomplete to select from commonly-used values.

As you can see from the example, the dropdown is rendered transparently over top of the existing UI.

Example at http://typeahead_bug.meteor.com/
Code at https://github.com/tlau/typeahead_bug

**Comment by jcanady20** [comment]
your missing the type ahead specific css. a quick google should give you what your looking for.

**Comment by tlau** [comment]
It'd be nice to have a pointer to the correct CSS in the README for this repo. I did a google search and found this one: https://github.com/bassjobsen/typeahead.js-bootstrap-css/blob/master/typeaheadjs.css
but it still doesn't look right. :(

**Comment by sergeyt** [comment]
@tlau demo app in this report has sample styles for bootstrap 3 UI framework, but they might be outdated

**Comment by pierreozoux** [comment]
+1 : it is not beautiful out of the box, and it should.

I'm Investigating to PR.

**Comment by pierreozoux** [comment]
@tlau This PR should give you a better understanding of the issue https://github.com/sergeyt/meteor-typeahead/pull/75
