### ISSUE TITLE
Multiple datasets example outdated

### ISSUE THREAD

**Issue by luisarroyo** [sergeyt/meteor-typeahead#71]
The multiple datasets example is outdated, I manage to make it work by using the following code (as in the demo page):
https://gist.github.com/luisarroyo/39a03a580cdefc67d985
<script src="https://gist.github.com/luisarroyo/39a03a580cdefc67d985.js"></script>

**Comment by sergeyt** [comment]
@luisarroyo please feel free to update example in [README](https://github.com/sergeyt/meteor-typeahead/blob/master/README.md) page

**Comment by abuddenb** [comment]
The multiple datasets demo is still broken; you also need to add `displayKey` as shown in @luisarroyo's gist.  Otherwise the text input will display a json representation of the user's choice.  Ex:

> {"_id":"NxTRP6KjLaHYuaAJe","name":"Los Angeles Clippers"}
