### ISSUE TITLE
Increase limit in suggestion list

### ISSUE THREAD

**Issue by imajus** [sergeyt/meteor-typeahead#74]
Is there any way I can control the limit of items in suggestion list? It seems like it's currently limited to 5. 

The problem is I have about 7 items like "First Item", "Second Item", "Third Item", "Fourth Item", "Fifth Item", "Sixth Item" and "Item". Let's say I want to choose an "Item". But when I enter "item" in search field I get only 5 first items. So apparently there's no way to choose an "Item" with that data source now.

**Comment by sergeyt** [comment]
@imajus try to specify `data-limit` attribute
