### ISSUE TITLE
Selected dataset undefined for multi-dataset

### ISSUE THREAD

**Issue by zaklampert** [sergeyt/meteor-typeahead#80]
search.html
```
<input id="recipeFilter" 
			 	class="form-control typeahead" 
			 	name="suggestions" 
			 	type="text" 
			 	data-sets="categories"
			 	data-template="suggestions" 
			 	data-value-key="name"
			 	data-selected="selected"
			 	placeholder="Search Recipes..."/>
```

search.js
```
Template.search.helpers({
	categories:function(){
		return[
			{
				name: 'products',
				valueKey: 'name',
				displayKey: 'name',
				local: function(){return Products.find().fetch();},
				header: '<h2>Recipes by Product</h2>',
				template: 'productSuggestions'
			},
			{
				name: 'recipe_groups',
				valueKey: 'name',
				displayKey: 'name',
				local: function(){return RecipeGroups.find().fetch();},
				header: '<h2>Recipes by Group</h2>'
			}
		]
	},
	selected:function(e, suggestion, dataset){
		//console.log(suggestion);
		console.log('dataset: '+dataset)
	}
})
```

Selecting an item logs "undefined" for dataset. "Suggestion" returns as...suggested.

**Comment by zaklampert** [comment]
to elaborate, the problem I'm having is not being able to access the specific category name in the event. 

For the time being, I have created templates that have a custom data-category-name in the event target, and doing my work after the 'click' event. This is problematic, however, since items can be selected without necessarily clicking on them.

```
Template.recipeSearch.events({
	'click .tt-selectable':function(e){
		
		var collection = $(e.currentTarget).data('collection')
		var group = $(e.currentTarget).data('group')
	
		Router.go('recipeFilter',{filt:collection,group:group})

	}
})
```

**Comment by JoarSvensson** [comment]
In the recent version of Typeahead.js, the event is now typeahead:select and not typeahead:selected which means it's not working as expected. https://github.com/twitter/typeahead.js/issues/300

**Comment by mvgalle** [comment]
The code you have provided uses "data-selected", you should change it to "data-select".
