### ISSUE TITLE
How to make server side search to be case insensitive?

### ISSUE THREAD

**Issue by kyooriouskoala** [sergeyt/meteor-typeahead#87]
Hi, I'm implementing a server side search on my project and just found out that the reason I had not been getting any search result back was due to case sensitivity issue.

I checked the [demo] (http://typeahead.meteor.com/) again and apparently it's also behaving the same.

With my limited knowledge, I tried to tweak `regex` in the search method based on [mongodb doc ](http://docs.mongodb.org/manual/reference/operator/query/regex/#regex-case-insensitive) but to no avail. Could you kindly share a solution to make it case insensitive for server side search, please? Thanks!

**Comment by sergeyt** [comment]
@kyooriouskoala mongo db supports case-insensitive **i** option for $regex query (see http://docs.mongodb.org/manual/reference/operator/query/regex/)

**Comment by kyooriouskoala** [comment]
I had been doing it the wrong way >.<  

Was concatenating the initial `regex` value in this manner `var newValue = regex + "i";` to make the output the same as what's written in [mongodb doc] (http://docs.mongodb.org/manual/reference/operator/query/regex/#regex-case-insensitive).

Turns out it should have been done this way: `var regex = new RegExp("^" + query, 'i');`

Found the solution from this [MDN site] (https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/RegExp).

Thanks.
