### ISSUE TITLE
Server side search to accept "flexible" query format like when using data-source attribute

### ISSUE THREAD

**Issue by kyooriouskoala** [sergeyt/meteor-typeahead#88]
Hi, I would like to use server side search but I just can't figure out how to make it to accept "flexible" query like when using data-source attribute. 

<h4>Docs in collection:</h4>
```javascript
{ _id: "jK2hcF4nhvDTLz2kk", name: "Queens Gravity Thunder Thumb" },
{ _id: "vca85Q6Hm65G52Xpb", name: "Queens City Thunder Thor" },
{ _id: "mGyRxhZFFshdeubve", name: "Queens Soldier Thunder Trie"}
```

<h4>:: data-source attribute</h4>
<b>Query: </b>
`queens thun`
or 
`quee th`

<b>Search result:</b>
```
Queens City Thunder Thor
Queens Gravity Thunder Thumb
Queens Soldier Thunder Trie
```

<h4>:: server side search</h4>
<b>Query: </b> 
`queens thun`

<b>Search result:</b>
nil

Below code snippet is taken from another package but it is still not as great as data-source attribute.
```javascript
var parts = query.trim().split(/[ \-\:]+/);
var regex = new RegExp("(" + parts.join('|') + ")", "ig");
````

Would it be possible to have server side search method to accept query like data-source attribute? If it's possible, please kindly share the solution. Thank you!

**Comment by sergeyt** [comment]
@kyooriouskoala I think you could try to reuse code of [bloodhound suggestion engine taken](https://github.com/twitter/typeahead.js/blob/master/doc/bloodhound.md) from typeahead.js. It should work in server-side environment. Also it is possible to expose `search` function within the package leveraging bloodhound suggestion engine that could run anywhere on client or server environments.

**Comment by sergeyt** [comment]
@kyooriouskoala I've just checked that your approach with regexp should work in chrome console with the code:

```javascript
var names = ["Queens Gravity Thunder Thumb", "Queens City Thunder Thor", "Queens Soldier Thunder Trie"]
var re = new RegExp("queens|th", "ig")
var result = names.filter(function(s){ return r.test(s) })
```
which produces the expected output.

I guess there is some bug somewhere in meteor mongo js module since such simple regexp must work in mongodb.

**Comment by kyooriouskoala** [comment]
Hi @sergeyt ,

The regexp does work in outputting that three results but it's not sorted smartly like what bloodhound would output.

If you notice the mentioned results with data-source attribute/bloodhound, they are sorted alphabetically - which is good. However, what makes it great is that it also rank the results that have most matches and put them on top.

Further example below.

<h4>:: data-source attribute/bloodhound</h4>
<b>Query:</b>
`queens thun trie`

<b>Search result:</b>
`Queens Soldier Thunder Trie`

<h4>:: server side search</h4>
<b>RegExp:</b>
```javascript
var parts = query.trim().split(/[ \-\:]+/);
var regex = new RegExp("(" + parts.join('|') + ")", "ig");
```
<b>Query:</b>
`queens thun trie`

<b>Search results:</b>
```
Queens City Thunder Thor
Queens Gravity Thunder Thumb
Queens Soldier Thunder Trie
```

I've taken a look at the bloodhound doc that you suggested but I'm still a novice when it comes to javascript in general. Therefore, I could only do trial and error in a noob way. 

Could you perhaps provide code example of what could have worked, in your opinion, to implement bloodhound for the server side search, please? Thanks!

**Comment by sergeyt** [comment]
@kyooriouskoala the example usage of bloodhound is in [index.js](https://github.com/sergeyt/meteor-typeahead/blob/master/index.js#L370) (see make_bloodhound function), note you need to take and add bloodhound.js into your application. Also note use of bloodhound is not suitable if you search in big collection.

**Comment by kyooriouskoala** [comment]
Thanks for the hint. I'll check out the [index.js] (https://github.com/sergeyt/meteor-typeahead/blob/master/index.js#L370).

> Also note use of bloodhound is not suitable if you search in big collection.

Do you happen to know roughly up to how many docs in a collection that is still alright for bloodhound to perform well?

I'm looking to search about 2 to 3k of docs, at the very least.

**Comment by sergeyt** [comment]
@kyooriouskoala 2-3k could be quite big if you have a lot search requests, 10-50 milliseconds per request should be good enough.
