### ISSUE TITLE
suggestion: autocomplete and spellcheck attribute values

### ISSUE THREAD

**Issue by lowenf** [sergeyt/meteor-typeahead#97]
should not be 'off' but set to 'false' in order for them to work in the current browsers. If I set them myself (by searching the whole project for the attributes) then they keep resetting after some time. Not sure how to fix this myself, but should be easy :)

**Comment by kristijanhusak** [comment]
`autocomplete="false"` is not working in Chrome 47.0.2526.111 (64-bit) . They probably fixed it in the meantime. I also tested Firefox with both `false` and `off`, and it's working. I'm only not sure about Safari.

**Comment by sergeyt** [comment]
I think this could be easily handled by application, so I suggest to remove [this line](https://github.com/sergeyt/meteor-typeahead/blob/master/typeahead.bundle.js#L2399) from typeahead bundle at all.

**Comment by sergeyt** [comment]
please welcome to send PR

**Comment by kristijanhusak** [comment]
Agree. Will create PR soon.
